# Generated by Django 3.1.13 on 2022-03-03 04:36

from django.db import migrations, models
import menus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', menus.models.CharFieldTrim(error_messages={'unique': 'The module already exists'}, max_length=15)),
            ],
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_module'),
        ),
    ]
