# Generated by Django 3.1.13 on 2021-10-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(error_messages={'unique': 'The module already exists'}, max_length=15),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_module'),
        ),
    ]
