# Generated by Django 4.0.5 on 2022-06-02 00:24

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='module',
            name='unique_module',
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_module'),
        ),
    ]
