# Generated by Django 4.0.5 on 2022-06-02 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_remove_module_unique_module_module_unique_module'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='module',
            name='unique_module',
        ),
    ]
