# Generated by Django 4.0.5 on 2022-06-22 01:24

from django.db import migrations, models
import django.db.models.deletion
import menus.models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_module_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', menus.models.CharFieldTrim(error_messages={'unique': 'The module already exists'}, max_length=15)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.module')),
            ],
        ),
    ]
