# Generated by Django 4.0.5 on 2022-06-22 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='menus.menu'),
        ),
    ]
