# Generated by Django 4.0.5 on 2022-06-25 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_module_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='position',
            new_name='order',
        ),
    ]
