# Generated by Django 4.0.5 on 2022-06-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_rename_position_module_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
