# Generated by Django 4.0.5 on 2022-10-08 03:58

from django.db import migrations, models
import django.db.models.deletion
import menus.models.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_remove_module_order_menu_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='menus.module'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=menus.models.custom_fields.CharFieldTrim(error_messages={'unique': 'The Module already exists'}, max_length=15),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=menus.models.custom_fields.CharFieldTrim(error_messages={'unique': 'The Module already exists'}, max_length=15, unique=True),
        ),
    ]
